import verificador
monitor = verificador.Monitor()
log = verificador.Log()
log.printLog("Criada classe Leitora. ID: 1")
log.printLog("Criada classe Leitora. ID: 2")
log.printLog("Criada classe Leitora. ID: 3")
log.printLog("Criada classe Leitora. ID: 4")
log.printLog("Criada classe Leitora. ID: 5")
log.printLog("Criada classe Leitora. ID: 6")
log.printLog("Criada classe Leitora. ID: 7")
log.printLog("Criada classe Leitora. ID: 8")
log.printLog("Criada classe Escritora. ID: 1")
log.printLog("Criada classe Escritora. ID: 2")
log.printLog("Criada classe LeitoraEscritora. ID: 1")
log.printLog("Criada classe LeitoraEscritora. ID: 2")
log.printLog("Criada classe LeitoraEscritora. ID: 3")
log.printLog("Criada classe LeitoraEscritora. ID: 4")
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.leitorBloqueado(6)
monitor.leitorBloqueado(5)
monitor.leitorBloqueado(4)
monitor.leitorBloqueado(2)
monitor.leitorBloqueado(3)
monitor.leitorBloqueado(1)
monitor.leitorBloqueado(4)
monitor.leitorBloqueado(3)
monitor.leitorBloqueado(2)
monitor.leitorBloqueado(8)
monitor.leitorBloqueado(1)
monitor.liberaEscritor(2)
monitor.leitorLendo(7)
monitor.leitorLendo(1)
monitor.leitorLendo(8)
monitor.leitorLendo(2)
monitor.leitorLendo(3)
monitor.leitorLendo(4)
monitor.leitorLendo(1)
monitor.leitorLendo(3)
monitor.leitorLendo(2)
monitor.leitorLendo(4)
monitor.leitorLendo(5)
monitor.leitorLendo(6)
log.printLog("Leitora 7 leu 2.")
log.printLog("Leitora 2 leu 2.")
log.printLog("Leitora 1 leu 2.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 3 leu 2.")
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é primo.")
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é par.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(3)
monitor.liberaLeitor(5)
monitor.liberaLeitor(2)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(7)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.escritorBloqueado(3)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(4)
monitor.leitorLendo(5)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(1)
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(2)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 3 leu 2.")
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(7)
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("Leitora 7 leu 2.")
monitor.leitorLendo(2)
log.printLog("2 é primo.")
monitor.leitorLendo(3)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(8)
log.printLog("2 é par.")
log.printLog("2 é par.")
log.printLog("Leitora 8 leu 2.")
monitor.liberaLeitor(7)
log.printLog("2 é par.")
log.printLog("2 é par.")
monitor.liberaLeitor(3)
log.printLog("2 é primo.")
monitor.liberaLeitor(6)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.liberaLeitor(4)
monitor.liberaLeitor(8)
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.escritorBloqueado(2)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(3)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 3 leu 2.")
monitor.leitorLendo(5)
log.printLog("Leitora 2 leu 2.")
monitor.leitorLendo(4)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(3)
log.printLog("Leitora 7 leu 2.")
log.printLog("Leitora 3 leu 2.")
monitor.leitorLendo(8)
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(1)
log.printLog("2 é par.")
monitor.liberaLeitor(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.escritorBloqueado(1)
monitor.liberaLeitor(8)
monitor.liberaLeitor(7)
monitor.liberaLeitor(3)
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(1)
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(1)
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(6)
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(5)
log.printLog("Leitora 3 leu 2.")
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(2)
log.printLog("2 é primo.")
log.printLog("Leitora 2 leu 2.")
monitor.leitorLendo(7)
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("Leitora 1 leu 2.")
monitor.liberaLeitor(3)
monitor.liberaLeitor(5)
log.printLog("2 é primo.")
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(4)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(4)
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
monitor.leitorLendo(3)
log.printLog("1 não é primo.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 3 leu 1.")
monitor.leitorLendo(6)
log.printLog("Leitora 4 leu 1.")
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("1 não é primo.")
log.printLog("Leitora 2 leu 1.")
monitor.leitorLendo(1)
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
log.printLog("LeitoraEscritora 2 leu 1.")
monitor.leitorLendo(4)
log.printLog("1 é ímpar.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("LeitoraEscritora 3 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(7)
log.printLog("1 é ímpar.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 2.")
monitor.escritorBloqueado(3)
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 2.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
monitor.leitorLendo(2)
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 2 leu 1.")
monitor.leitorLendo(3)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
log.printLog("LeitoraEscritora 3 leu 1.")
monitor.liberaLeitor(4)
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(6)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 2.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 2.")
monitor.leitorBloqueado(1)
monitor.liberaEscritor(3)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
monitor.leitorLendo(6)
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 6 leu 1.")
monitor.leitorLendo(5)
log.printLog("LeitoraEscritora 2 leu 1.")
log.printLog("Leitora 5 leu 1.")
monitor.leitorLendo(2)
log.printLog("1 não é primo.")
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("1 não é primo.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 1 leu 1.")
monitor.leitorLendo(7)
log.printLog("Leitora 4 leu 1.")
monitor.leitorLendo(3)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
log.printLog("LeitoraEscritora 3 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(2)
log.printLog("1 não é primo.")
monitor.escritorBloqueado(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(2)
monitor.liberaLeitor(6)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(1)
monitor.liberaLeitor(7)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.escritorBloqueado(3)
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 2.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 2.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 8.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 8.")
log.printLog("8 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 8.")
log.printLog("8 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 16.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 16.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
monitor.liberaLeitor(6)
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
monitor.leitorLendo(2)
log.printLog("Leitora 4 leu 1.")
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("1 não é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 1 leu 1.")
log.printLog("Leitora 7 leu 1.")
monitor.leitorLendo(4)
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 4 leu 1.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(7)
log.printLog("Leitora 3 leu 1.")
monitor.liberaLeitor(4)
log.printLog("1 é ímpar.")
monitor.liberaLeitor(2)
log.printLog("1 não é primo.")
monitor.liberaLeitor(5)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.leitorBloqueado(1)
monitor.liberaEscritor(4)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
monitor.liberaLeitor(1)
log.printLog("Leitora 4 leu 1.")
monitor.escritorBloqueado(1)
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
monitor.leitorLendo(3)
log.printLog("Leitora 1 leu 1.")
monitor.leitorLendo(7)
log.printLog("Leitora 3 leu 1.")
monitor.leitorLendo(4)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(5)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(2)
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("LeitoraEscritora 1 leu 1.")
monitor.leitorLendo(1)
log.printLog("1 é ímpar.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 1 leu 1.")
monitor.leitorLendo(7)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(3)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(6)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
monitor.liberaLeitor(4)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(6)
log.printLog("1 é ímpar.")
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(4)
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("2 é par.")
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(7)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(4)
log.printLog("Leitora 1 leu 2.")
monitor.escritorBloqueado(4)
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
monitor.leitorLendo(4)
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
log.printLog("2 é primo.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(3)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
monitor.leitorLendo(6)
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(7)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(3)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(2)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(3)
log.printLog("2 é par.")
monitor.liberaLeitor(6)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(7)
log.printLog("LeitoraEscritora 1 leu 1.")
monitor.leitorLendo(1)
log.printLog("Leitora 7 leu 1.")
monitor.leitorLendo(3)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 é ímpar.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 4 leu 1.")
monitor.leitorLendo(2)
log.printLog("Leitora 6 leu 1.")
monitor.leitorLendo(5)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(2)
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(5)
monitor.liberaLeitor(6)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(7)
log.printLog("Leitora 3 leu 2.")
monitor.leitorLendo(6)
log.printLog("Leitora 7 leu 2.")
monitor.leitorLendo(1)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(1)
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.escritorBloqueado(4)
monitor.leitorLendo(4)
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(1)
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(4)
log.printLog("Leitora 3 leu 2.")
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(6)
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 6 leu 2.")
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(5)
monitor.liberaLeitor(6)
monitor.liberaLeitor(2)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.liberaLeitor(7)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.leitorLendo(4)
log.printLog("Leitora 1 leu 2.")
monitor.leitorLendo(7)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
monitor.leitorLendo(6)
log.printLog("Leitora 5 leu 2.")
monitor.liberaLeitor(3)
monitor.liberaLeitor(2)
log.printLog("Leitora 6 leu 2.")
monitor.liberaLeitor(7)
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(6)
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(4)
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(1)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.liberaLeitor(1)
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(6)
monitor.leitorLendo(4)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 2.")
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(4)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(5)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(5)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(3)
monitor.leitorLendo(7)
log.printLog("Leitora 3 leu 1.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("1 não é primo.")
monitor.liberaLeitor(1)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 não é primo.")
monitor.escritorBloqueado(1)
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(7)
monitor.liberaLeitor(5)
monitor.liberaLeitor(3)
monitor.liberaLeitor(1)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
log.printLog("2 é par.")
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(6)
monitor.leitorLendo(2)
log.printLog("Leitora 1 leu 2.")
monitor.leitorLendo(7)
log.printLog("Leitora 2 leu 2.")
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(4)
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(1)
monitor.liberaLeitor(7)
monitor.liberaLeitor(2)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(5)
monitor.leitorLendo(1)
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(3)
log.printLog("Leitora 1 leu 2.")
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("2 é primo.")
log.printLog("Leitora 7 leu 2.")
monitor.leitorLendo(6)
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(7)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.liberaLeitor(5)
monitor.liberaLeitor(3)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.escritorBloqueado(4)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(5)
log.printLog("Leitora 2 leu 2.")
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(3)
log.printLog("2 é par.")
monitor.leitorLendo(6)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(7)
monitor.leitorLendo(2)
log.printLog("Leitora 7 leu 1.")
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(2)
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
monitor.liberaLeitor(3)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(7)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 7 leu 2.")
monitor.leitorLendo(1)
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 2 leu 2.")
monitor.leitorLendo(5)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(4)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("Leitora 4 leu 2.")
monitor.liberaLeitor(7)
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
log.printLog("2 é primo.")
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(1)
monitor.liberaLeitor(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
monitor.leitorLendo(5)
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 5 leu 2.")
log.printLog("Leitora 7 leu 2.")
monitor.leitorLendo(1)
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(6)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é par.")
monitor.leitorLendo(1)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(4)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(1)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.escritorBloqueado(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(6)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("1 não é primo.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(4)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(7)
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.leitorLendo(1)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(5)
log.printLog("Leitora 2 leu 2.")
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(4)
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
monitor.leitorLendo(3)
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.liberaLeitor(6)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(1)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
monitor.leitorLendo(2)
log.printLog("Leitora 5 leu 2.")
monitor.leitorLendo(1)
log.printLog("Leitora 2 leu 2.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é par.")
monitor.leitorLendo(6)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(3)
log.printLog("Leitora 6 leu 2.")
monitor.leitorLendo(4)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 4 leu 2.")
monitor.liberaLeitor(4)
log.printLog("2 é primo.")
log.printLog("2 é primo.")
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(1)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(2)
monitor.leitorLendo(1)
log.printLog("Leitora 2 leu 2.")
monitor.leitorLendo(5)
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.leitorLendo(4)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é primo.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("2 é par.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("LeitoraEscritora 4 leu 2.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
log.printLog("2 é par.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(1)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(2)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
monitor.leitorLendo(4)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.liberaLeitor(5)
monitor.liberaLeitor(2)
monitor.liberaLeitor(1)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(3)
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
log.printLog("Leitora 3 leu 1.")
monitor.leitorLendo(7)
monitor.leitorLendo(4)
log.printLog("1 não é primo.")
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.liberaLeitor(3)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.escritorBloqueado(4)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 1 leu 1.")
monitor.leitorLendo(4)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(1)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.liberaLeitor(7)
monitor.liberaLeitor(3)
monitor.liberaLeitor(5)
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(2)
monitor.leitorLendo(1)
log.printLog("Leitora 2 leu 1.")
log.printLog("1 não é primo.")
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 1.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(5)
monitor.liberaLeitor(6)
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
log.printLog("2 é par.")
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(1)
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
log.printLog("LeitoraEscritora 1 leu 2.")
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(4)
monitor.liberaLeitor(5)
monitor.liberaLeitor(7)
monitor.liberaLeitor(3)
monitor.liberaLeitor(6)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(1)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.liberaEscritor(2)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 2.")
log.printLog("2 é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(4)
log.printLog("LeitoraEscritora 4 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(7)
log.printLog("Leitora 7 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(2)
log.printLog("Leitora 2 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 1 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(4)
log.printLog("Leitora 4 leu 2.")
log.printLog("2 é primo.")
monitor.leitorLendo(5)
monitor.liberaLeitor(4)
monitor.liberaLeitor(1)
log.printLog("Leitora 5 leu 2.")
log.printLog("2 é primo.")
monitor.escritorBloqueado(1)
monitor.liberaLeitor(2)
monitor.liberaLeitor(1)
monitor.liberaLeitor(6)
monitor.liberaLeitor(3)
monitor.liberaLeitor(7)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(5)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 4.")
monitor.liberaEscritor(1)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 4.")
monitor.liberaEscritor(4)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 4.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 4.")
log.printLog("4 é par.")
monitor.liberaLeitor(3)
monitor.escritorBloqueado(3)
log.printLog("4 é par.")
monitor.liberaLeitor(2)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 8.")
monitor.escritorBloqueado(3)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 8.")
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("Escritora 2 escreveu.")
monitor.escritorBloqueado(1)
monitor.liberaEscritor(2)
monitor.escritorEscrevendo(1)
log.printLog("Escritora 1 escreveu.")
monitor.liberaEscritor(1)
monitor.leitorLendo(8)
log.printLog("Leitora 8 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(8)
monitor.leitorLendo(2)
monitor.leitorLendo(4)
log.printLog("Leitora 2 leu 1.")
monitor.leitorLendo(1)
log.printLog("LeitoraEscritora 4 leu 1.")
log.printLog("LeitoraEscritora 1 leu 1.")
monitor.leitorLendo(7)
log.printLog("1 não é primo.")
log.printLog("Leitora 7 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(4)
log.printLog("1 é ímpar.")
log.printLog("Leitora 4 leu 1.")
log.printLog("1 não é primo.")
log.printLog("1 é ímpar.")
monitor.leitorLendo(3)
log.printLog("Leitora 3 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(5)
log.printLog("Leitora 5 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(1)
log.printLog("Leitora 1 leu 1.")
log.printLog("1 não é primo.")
monitor.leitorLendo(6)
log.printLog("Leitora 6 leu 1.")
log.printLog("1 não é primo.")
monitor.liberaLeitor(1)
monitor.liberaLeitor(5)
monitor.liberaLeitor(3)
monitor.liberaLeitor(4)
monitor.escritorBloqueado(4)
monitor.liberaLeitor(4)
monitor.liberaLeitor(1)
monitor.escritorBloqueado(1)
monitor.liberaLeitor(7)
monitor.liberaLeitor(2)
monitor.liberaLeitor(6)
monitor.escritorEscrevendo(4)
log.printLog("LeitoraEscritora 4 escreveu 2.")
monitor.liberaEscritor(4)
monitor.escritorEscrevendo(1)
log.printLog("LeitoraEscritora 1 escreveu 2.")
monitor.liberaEscritor(1)
monitor.leitorLendo(2)
log.printLog("LeitoraEscritora 2 leu 2.")
log.printLog("2 é par.")
monitor.leitorLendo(3)
log.printLog("LeitoraEscritora 3 leu 2.")
log.printLog("2 é par.")
monitor.liberaLeitor(2)
monitor.escritorBloqueado(2)
monitor.liberaLeitor(3)
monitor.escritorEscrevendo(3)
log.printLog("LeitoraEscritora 3 escreveu 4.")
monitor.escritorBloqueado(2)
monitor.liberaEscritor(3)
monitor.escritorEscrevendo(2)
log.printLog("LeitoraEscritora 2 escreveu 4.")
monitor.liberaEscritor(2)
